attack: wanet
attack_label_trans: all2one
attack_target: 0
pratio: 0.23
cross_ratio: 2  # rho_a = pratio, rho_n = pratio * cross_ratio
random_rotation: 10
random_crop: 5
s: 0.5
k: 4
grid_rescale: 1
lr_scheduler: MultiStepLR
steplr_milestones:
  - 100
  - 200
  - 300
  - 400
steplr_gamma: 0.1

dataset_path: ../data/datasets
pin_memory: True
non_blocking: True
batch_size: 128
num_workers: 8
device: cuda:0
frequency_save: 0
epochs: 100
random_seed: 0
client_optimizer: sgd
lr: 0.01
sgd_momentum: 0.9
wd: 0.0005