device: cuda:0
amp: True
pin_memory: True
non_blocking: True
prefetch: False

checkpoint_load:
checkpoint_save:
log:
dataset_path: ../data/datasets
# dataset: cifar10

epochs: 100
batch_size: 256
num_workers: 8
lr: 0.01
lr_scheduler: CosineAnnealingLR
# model: preactresnet18

client_optimizer: sgd
sgd_momentum: 0.9 
wd: 0.0005
frequency_save: 0
random_seed: 0
ratio: 0.05
index: 

